@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User Input;
if (valid input) then (yes)
  :Check duplicate patient;
  if (no duplicate patient) then (yes)
    :Add patient into ToothTracker;
  else (no)
    :Throw error message;
  endif
else (no)
  :Throw error message;
endif
stop
@enduml
