@startuml
!include style.puml
'https://plantuml.com/sequence-diagram

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":SearchDentistCommandParser" as SearchDentistCmdParser LOGIC_COLOR
participant ":DentistNameContainsKeywordsPredicate" as Predicate LOGIC_COLOR
end box

[-> LogicManager : execute("search-dentist John")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("search-dentist John")
activate AddressBookParser

SearchDentistCmdParser -> Predicate : DentistNameContainsKeywordsPredicate("keyword")
activate Predicate

Predicate -> Predicate : switchOnKeyword("keyword")
activate Predicate
Predicate --> Predicate
deactivate Predicate

Predicate --> SearchDentistCmdParser
deactivate Predicate

create SearchDentistCommand
SearchDentistCmdParser -> SearchDentistCommand : SearchDentistCommand(predicate)
activate SearchDentistCommand
SearchDentistCommand --> SearchDentistCmdParser
deactivate SearchDentistCommand

SearchDentistCmdParser --> LogicManager
deactivate SearchDentistCmdParser

LogicManager -> SearchDentistCommand : execute(model)
activate SearchDentistCommand

SearchDentistCommand -> Model : searchDentist(predicate)
activate Model
Model --> SearchDentistCommand
deactivate Model

SearchDentistCommand --> LogicManager
deactivate SearchDentistCommand

[<--LogicManager
deactivate LogicManager
@enduml