@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR
skinparam groupInheritance 3

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PatientListPanel
Class PatientCard
Class DentistListPanel
Class DentistCard
Class AppointmentListPanel
Class AppointmentCard
Class StatusBarFooter
Class CommandBox
Class QuickNotes
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PatientListPanel
MainWindow *-down-> "1" DentistListPanel
MainWindow *-down-> "1" AppointmentListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" QuickNotes
MainWindow --> "0..1" HelpWindow

PatientListPanel -down-> "*" PatientCard
DentistListPanel -down-> "*" DentistCard
AppointmentListPanel -down-> "*" AppointmentCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PatientListPanel --|> UiPart
DentistListPanel --|> UiPart
AppointmentListPanel --|> UiPart
PatientCard --|> UiPart
DentistCard --|> UiPart
AppointmentCard --|> UiPart
QuickNotes --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

PatientCard ..> Model
DentistCard ..> Model
AppointmentCard ...> Model

UiManager -right-> Logic
MainWindow -left-> Logic

AppointmentListPanel -[hidden]left- DentistListPanel
DentistListPanel -[hidden]left- PatientListPanel
PatientListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml